from turtle import Turtle, Screen
timmy = Turtle()
screen = Screen()
while True:
    timmy.shape("turtle")
    timmy.color("chocolate")
    timmy.forward(100)
    timmy.left(150)
    timmy.forward(100)
    timmy.left(50)
    timmy.forward(100)
    timmy.left(50)
    timmy.forward(100)
    timmy.left(150)
print(timmy)
print(screen.canvheight)
screen.exitonclick()